package TestNG;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class TestNG_Class 
{
	//TestNG is a java unit framework used for writing/designing of Test classes
	
	//emailable-report is generated by the TestNG 
	// this report will show how many test cases are passed, failed, 
 
	@Test
  public void ooenFacebook()
  {
	  
			//Steps for opening browser
			// 1. Name of the browser
			// 2. Path of the ChromeDriver.exe file

			System.setProperty("webdriver.chrome.driver","D:\\Software Testing\\Chrome Driver\\chromedriver_win32\\chromedriver.exe");


			//Creating an object of ChromeDriver with the reference of WebDriver

			WebDriver driver = new ChromeDriver();
			
			driver.get("https://Facebook.com");
			
  }
}
